### ISSUE TITLE
Question more than issue

### ISSUE THREAD

**Issue by tinuroth** [mworchel/openmesh-nuget#1]
Any chance that we get an OpenMesh Nuget package for VS 2017, toolset v141, any time soon? Ideally also updated to latest OpenMesh, v7.1. Would be great! :-)

Cheers,
Martin

**Comment by mworchel** [comment]
Yes, I'm working on a small build script to generate the packages automatically as the 6.2 package required too much manual work. I will be able to generate packages for VS 2013/2015/2017 and also the recent OpenMesh versions. Can't give any final date, though.

**Comment by mworchel** [comment]
I uploaded versions 6.2, 6.3, 7.0 and 7.1 for v120, v140 and v141 toolset to NuGet. Only shared linking works at the moment, though. Referring to issue #2 .

**Comment by tinuroth** [comment]
Great! Thanks a lot, will give it a try! If addressing things within a day or two is what you mean with "can't give any final date", then I definitely like that kind of milestone. :-)

Unfortunately, I am mainly interested in static linkage, so looking for forward to the resolution of issue #2. And I fully understand if you "cannot give a final date" on that one, either. ;-)

**Comment by mworchel** [comment]
I mean it's something I wanted to do for a while now and if there's demand it increases the motivation, of course :)

I managed to get the static linkage working in version 7.1.1. It's already uploaded and currently being validated by NuGet. The linkage can be configured in the project properties under the "Referenced Packages" tab. Would be nice if you could try it out and report back if there are still any issues. Thanks!

**Comment by tinuroth** [comment]
I tried this and building works flawless, with both static and dynamic linkage. Thanks a lot!!!

I ran into other problems, though, unrelated to OpenMesh, so could not really try it out. But I am confident that it will work. Will keep you posted.

**Comment by tinuroth** [comment]
I tried this and building works flawless, with both static and dynamic linkage. Thanks a lot!!!

I ran into other problems, though, unrelated to OpenMesh, so could not really try it out. But I am confident that it will work. Will keep you posted.

**Comment by tinuroth** [comment]
I tried this and building works flawless, with both static and dynamic linkage. Thanks a lot!!!

I ran into other problems, though, unrelated to OpenMesh, so could not really try it out. But I am confident that it will work. Will keep you posted.
